### ISSUE TITLE
Add remote continuous integration.

### ISSUE THREAD

**Issue by beckyconning** [slamdata/purescript-aff-reattempt#1]

**Comment by daira** [comment]
I've found Travis-CI pretty easy to set up. I've only used it for Python and C++, but the way it works (using a new VM instance for each build) should make it straightforward to set up for any language, and it integrates well with github.

**Comment by jdegoes** [comment]
I turned on Travis CI for the repo. What happens next (for me) is usually copying some other PureScript .travis.yml file. :smile:
